[package]
name = "bug-buster"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29", features = ["all-widgets"] }
crossterm = "0.29"
inquire = "0.7.5"
rand = "0.9.2"
once_cell = "1.21.3"
